!SESSION 2014-09-26 21:14:06.243 -----------------------------------------------
eclipse.buildId=4.3.2.M20140221-1700
java.version=1.7.0_67
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.standard.product -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.standard.product -data C:\Users\Matthew\Development\Python\repos\CodeForGood2014\server_workspace -product org.eclipse.epp.package.standard.product

!ENTRY org.eclipse.ui.navigator 2 0 2014-09-26 21:15:44.531
!MESSAGE Can't find Navigator Content Descriptor with id: org.eclipse.jst.servlet.ui.EnhancedJavaRendering

!ENTRY org.eclipse.egit.ui 2 0 2014-09-26 21:15:46.541
!MESSAGE Warning: EGit couldn't detect the installation path "gitPrefix" of native Git. Hence EGit can't respect system level
Git settings which might be configured in ${gitPrefix}/etc/gitconfig under the native Git installation directory.
The most important of these settings is core.autocrlf. Git for Windows by default sets this parameter to true in
this system level configuration. The Git installation location can be configured on the
Team > Git > Configuration preference page's 'System Settings' tab.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.egit.ui 2 0 2014-09-26 21:15:46.543
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\Matthew'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2014-09-26 21:17:26.810
!MESSAGE Information about process of adding new interpreter:
- Opening dialog to request executable (or jar).
- Chosen interpreter (name and file):'Tuple [C:\Program Files\Anaconda\python.exe -- C:\Program Files\Anaconda\python.exe]
- Ok, file is non-null. Getting info on:C:\Program Files\Anaconda\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  "C:\Program Files\Anaconda\python.exe" -u C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc\interpreterInfo.py
- Setting task name:Making pythonpath environment... "C:\Program Files\Anaconda\python.exe" -u C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc\interpreterInfo.py
- Setting task name:Making exec... "C:\Program Files\Anaconda\python.exe" -u C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc\interpreterInfo.py
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Success getting the info. Result:<xml>
<name>C:\Program Files\Anaconda\python.exe</name>
<version>2.7</version>
<executable>C:\Program Files\Anaconda\python.exe</executable>
<lib>C:\Program Files\Anaconda</lib>
<lib>C:\Users\Matthew\Development\Python\repos\probedb\AppEngine_workspace\AppEngineProject\probemanager</lib>
<lib>C:\Program Files\Anaconda\Lib\site-packages</lib>
<lib>C:\Program Files\Anaconda\DLLs</lib>
<lib>C:\Program Files\Anaconda\lib</lib>
<lib>C:\Program Files\Anaconda\lib\lib-tk</lib>
<lib>C:\Program Files\Anaconda\lib\site-packages\PIL</lib>
<lib>C:\Program Files\Anaconda\lib\site-packages\win32</lib>
<lib>C:\Program Files\Anaconda\lib\site-packages\win32\lib</lib>
<lib>C:\Program Files\Anaconda\lib\site-packages\Pythonwin</lib>
<lib>C:\Program Files\Anaconda\lib\site-packages\runipy-0.1.0-py2.7.egg</lib>
<lib>C:\Program Files\Anaconda\lib\site-packages\setuptools-3.6-py2.7.egg</lib>
<lib>C:\Program Files\Anaconda\Lib\site-packages\runipy-0.1.0-py2.7.egg</lib>
<lib>C:\Program Files\Anaconda\Lib\site-packages\setuptools-3.6-py2.7.egg</lib>
<forced_lib>Image</forced_lib>
<forced_lib>OpenGL</forced_lib>
<forced_lib>__builtin__</forced_lib>
<forced_lib>__main__</forced_lib>
<forced_lib>_ast</forced_lib>
<forced_lib>_bisect</forced_lib>
<forced_lib>_bytesio</forced_lib>
<forced_lib>_codecs</forced_lib>
<forced_lib>_codecs_cn</forced_lib>
<forced_lib>_codecs_hk</forced_lib>
<forced_lib>_codecs_iso2022</forced_lib>
<forced_lib>_codecs_jp</forced_lib>
<forced_lib>_codecs_kr</forced_lib>
<forced_lib>_codecs_tw</forced_lib>
<forced_lib>_collections</forced_lib>
<forced_lib>_csv</forced_lib>
<forced_lib>_fileio</forced_lib>
<forced_lib>_functools</forced_lib>
<forced_lib>_heapq</forced_lib>
<forced_lib>_hotshot</forced_lib>
<forced_lib>_io</forced_lib>
<forced_lib>_json</forced_lib>
<forced_lib>_locale</forced_lib>
<forced_lib>_lsprof</forced_lib>
<forced_lib>_md5</forced_lib>
<forced_lib>_multibytecodec</forced_lib>
<forced_lib>_random</forced_lib>
<forced_lib>_sha</forced_lib>
<forced_lib>_sha256</forced_lib>
<forced_lib>_sha512</forced_lib>
<forced_lib>_sre</forced_lib>
<forced_lib>_struct</forced_lib>
<forced_lib>_subprocess</forced_lib>
<forced_lib>_symtable</forced_lib>
<forced_lib>_warnings</forced_lib>
<forced_lib>_weakref</forced_lib>
<forced_lib>_winreg</forced_lib>
<forced_lib>array</forced_lib>
<forced_lib>astropy</forced_lib>
<forced_lib>astropy.units</forced_lib>
<forced_lib>audioop</forced_lib>
<forced_lib>binascii</forced_lib>
<forced_lib>cPickle</forced_lib>
<forced_lib>cStringIO</forced_lib>
<forced_lib>cmath</forced_lib>
<forced_lib>datetime</forced_lib>
<forced_lib>email</forced_lib>
<forced_lib>errno</forced_lib>
<forced_lib>exceptions</forced_lib>
<forced_lib>future_builtins</forced_lib>
<forced_lib>gc</forced_lib>
<forced_lib>hashlib</forced_lib>
<forced_lib>imageop</forced_lib>
<forced_lib>imp</forced_lib>
<forced_lib>itertools</forced_lib>
<forced_lib>marshal</forced_lib>
<forced_lib>math</forced_lib>
<forced_lib>mmap</forced_lib>
<forced_lib>msvcrt</forced_lib>
<forced_lib>nose</forced_lib>
<forced_lib>nose.tools</forced_lib>
<forced_lib>nt</forced_lib>
<forced_lib>numpy</forced_lib>
<forced_lib>operator</forced_lib>
<forced_lib>os</forced_lib>
<forced_lib>os.path</forced_lib>
<forced_lib>parser</forced_lib>
<forced_lib>pytest</forced_lib>
<forced_lib>scipy</forced_lib>
<forced_lib>signal</forced_lib>
<forced_lib>socket</forced_lib>
<forced_lib>strop</forced_lib>
<forced_lib>sys</forced_lib>
<forced_lib>thread</forced_lib>
<forced_lib>time</forced_lib>
<forced_lib>werkzeug</forced_lib>
<forced_lib>wx</forced_lib>
<forced_lib>wxPython</forced_lib>
<forced_lib>xxsubtype</forced_lib>
<forced_lib>zipimport</forced_lib>
<forced_lib>zlib</forced_lib>
</xml>

!STACK 0
java.lang.RuntimeException: Information about process of adding new interpreter:
- Opening dialog to request executable (or jar).
- Chosen interpreter (name and file):'Tuple [C:\Program Files\Anaconda\python.exe -- C:\Program Files\Anaconda\python.exe]
- Ok, file is non-null. Getting info on:C:\Program Files\Anaconda\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  "C:\Program Files\Anaconda\python.exe" -u C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc\interpreterInfo.py
- Setting task name:Making pythonpath environment... "C:\Program Files\Anaconda\python.exe" -u C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc\interpreterInfo.py
- Setting task name:Making exec... "C:\Program Files\Anaconda\python.exe" -u C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc\interpreterInfo.py
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Success getting the info. Result:<xml>
<name>C:\Program Files\Anaconda\python.exe</name>
<version>2.7</version>
<executable>C:\Program Files\Anaconda\python.exe</executable>
<lib>C:\Program Files\Anaconda</lib>
<lib>C:\Users\Matthew\Development\Python\repos\probedb\AppEngine_workspace\AppEngineProject\probemanager</lib>
<lib>C:\Program Files\Anaconda\Lib\site-packages</lib>
<lib>C:\Program Files\Anaconda\DLLs</lib>
<lib>C:\Program Files\Anaconda\lib</lib>
<lib>C:\Program Files\Anaconda\lib\lib-tk</lib>
<lib>C:\Program Files\Anaconda\lib\site-packages\PIL</lib>
<lib>C:\Program Files\Anaconda\lib\site-packages\win32</lib>
<lib>C:\Program Files\Anaconda\lib\site-packages\win32\lib</lib>
<lib>C:\Program Files\Anaconda\lib\site-packages\Pythonwin</lib>
<lib>C:\Program Files\Anaconda\lib\site-packages\runipy-0.1.0-py2.7.egg</lib>
<lib>C:\Program Files\Anaconda\lib\site-packages\setuptools-3.6-py2.7.egg</lib>
<lib>C:\Program Files\Anaconda\Lib\site-packages\runipy-0.1.0-py2.7.egg</lib>
<lib>C:\Program Files\Anaconda\Lib\site-packages\setuptools-3.6-py2.7.egg</lib>
<forced_lib>Image</forced_lib>
<forced_lib>OpenGL</forced_lib>
<forced_lib>__builtin__</forced_lib>
<forced_lib>__main__</forced_lib>
<forced_lib>_ast</forced_lib>
<forced_lib>_bisect</forced_lib>
<forced_lib>_bytesio</forced_lib>
<forced_lib>_codecs</forced_lib>
<forced_lib>_codecs_cn</forced_lib>
<forced_lib>_codecs_hk</forced_lib>
<forced_lib>_codecs_iso2022</forced_lib>
<forced_lib>_codecs_jp</forced_lib>
<forced_lib>_codecs_kr</forced_lib>
<forced_lib>_codecs_tw</forced_lib>
<forced_lib>_collections</forced_lib>
<forced_lib>_csv</forced_lib>
<forced_lib>_fileio</forced_lib>
<forced_lib>_functools</forced_lib>
<forced_lib>_heapq</forced_lib>
<forced_lib>_hotshot</forced_lib>
<forced_lib>_io</forced_lib>
<forced_lib>_json</forced_lib>
<forced_lib>_locale</forced_lib>
<forced_lib>_lsprof</forced_lib>
<forced_lib>_md5</forced_lib>
<forced_lib>_multibytecodec</forced_lib>
<forced_lib>_random</forced_lib>
<forced_lib>_sha</forced_lib>
<forced_lib>_sha256</forced_lib>
<forced_lib>_sha512</forced_lib>
<forced_lib>_sre</forced_lib>
<forced_lib>_struct</forced_lib>
<forced_lib>_subprocess</forced_lib>
<forced_lib>_symtable</forced_lib>
<forced_lib>_warnings</forced_lib>
<forced_lib>_weakref</forced_lib>
<forced_lib>_winreg</forced_lib>
<forced_lib>array</forced_lib>
<forced_lib>astropy</forced_lib>
<forced_lib>astropy.units</forced_lib>
<forced_lib>audioop</forced_lib>
<forced_lib>binascii</forced_lib>
<forced_lib>cPickle</forced_lib>
<forced_lib>cStringIO</forced_lib>
<forced_lib>cmath</forced_lib>
<forced_lib>datetime</forced_lib>
<forced_lib>email</forced_lib>
<forced_lib>errno</forced_lib>
<forced_lib>exceptions</forced_lib>
<forced_lib>future_builtins</forced_lib>
<forced_lib>gc</forced_lib>
<forced_lib>hashlib</forced_lib>
<forced_lib>imageop</forced_lib>
<forced_lib>imp</forced_lib>
<forced_lib>itertools</forced_lib>
<forced_lib>marshal</forced_lib>
<forced_lib>math</forced_lib>
<forced_lib>mmap</forced_lib>
<forced_lib>msvcrt</forced_lib>
<forced_lib>nose</forced_lib>
<forced_lib>nose.tools</forced_lib>
<forced_lib>nt</forced_lib>
<forced_lib>numpy</forced_lib>
<forced_lib>operator</forced_lib>
<forced_lib>os</forced_lib>
<forced_lib>os.path</forced_lib>
<forced_lib>parser</forced_lib>
<forced_lib>pytest</forced_lib>
<forced_lib>scipy</forced_lib>
<forced_lib>signal</forced_lib>
<forced_lib>socket</forced_lib>
<forced_lib>strop</forced_lib>
<forced_lib>sys</forced_lib>
<forced_lib>thread</forced_lib>
<forced_lib>time</forced_lib>
<forced_lib>werkzeug</forced_lib>
<forced_lib>wx</forced_lib>
<forced_lib>wxPython</forced_lib>
<forced_lib>xxsubtype</forced_lib>
<forced_lib>zipimport</forced_lib>
<forced_lib>zlib</forced_lib>
</xml>

	at org.python.pydev.core.log.Log.logInfo(Log.java:66)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor.getNewInputObject(AbstractInterpreterEditor.java:977)
	at org.python.copiedfromeclipsesrc.PythonListEditor.addPressed(PythonListEditor.java:132)
	at org.python.copiedfromeclipsesrc.PythonListEditor$1.widgetSelected(PythonListEditor.java:223)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:826)
	at org.eclipse.jface.window.Window.open(Window.java:802)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:215)
	at org.python.pydev.ui.PyProjectPythonDetails$ProjectInterpreterAndGrammarConfig$2.widgetSelected(PyProjectPythonDetails.java:235)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1098)
	at org.eclipse.swt.widgets.Link.wmNotifyChild(Link.java:1084)
	at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5617)
	at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1935)
	at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5169)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4667)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4990)
	at org.eclipse.swt.internal.win32.OS.CallWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(OS.java:2443)
	at org.eclipse.swt.widgets.Link.callWindowProc(Link.java:172)
	at org.eclipse.swt.widgets.Widget.wmLButtonUp(Widget.java:2075)
	at org.eclipse.swt.widgets.Control.WM_LBUTTONUP(Control.java:4995)
	at org.eclipse.swt.widgets.Link.WM_LBUTTONUP(Link.java:922)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4648)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4990)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2549)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3757)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:826)
	at org.eclipse.jface.window.Window.open(Window.java:802)
	at org.eclipse.ui.internal.handlers.WizardHandler$New.executeHandler(WizardHandler.java:259)
	at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:279)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:243)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:224)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:167)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:420)
	at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:157)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:140)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:611)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)

!ENTRY org.python.pydev.shared_core 1 1 2014-09-26 21:17:28.100
!MESSAGE Restoring info for: C:\Program Files\Anaconda\python.exe
!STACK 0
java.lang.RuntimeException: Restoring info for: C:\Program Files\Anaconda\python.exe
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.getInterpretersFromPersistedString(AbstractInterpreterManager.java:517)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.internalRecreateCacheGetInterpreterInfos(AbstractInterpreterManager.java:337)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:641)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Caused by: java.io.IOException: Expecting: C:\Users\Matthew\Development\Python\repos\CodeForGood2014\server_workspace\.metadata\.plugins\org.python.pydev\v1_18uivqhmb7t76vtsix84zcaw5\modulesKeys to exist (and be a file).
	at org.python.pydev.editor.codecompletion.revisited.ModulesManager.loadFromFile(ModulesManager.java:288)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.load(SystemModulesManager.java:371)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.getInterpretersFromPersistedString(AbstractInterpreterManager.java:515)
	... 4 more

!ENTRY org.python.pydev.shared_core 1 1 2014-09-26 21:17:51.347
!MESSAGE Finished restoring information for: C:\Program Files\Anaconda\python.exe at: C:\Users\Matthew\Development\Python\repos\CodeForGood2014\server_workspace\.metadata\.plugins\org.python.pydev\v1_18uivqhmb7t76vtsix84zcaw5
!STACK 0
java.lang.RuntimeException: Finished restoring information for: C:\Program Files\Anaconda\python.exe at: C:\Users\Matthew\Development\Python\repos\CodeForGood2014\server_workspace\.metadata\.plugins\org.python.pydev\v1_18uivqhmb7t76vtsix84zcaw5
	at org.python.pydev.core.log.Log.logInfo(Log.java:66)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.getInterpretersFromPersistedString(AbstractInterpreterManager.java:562)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.internalRecreateCacheGetInterpreterInfos(AbstractInterpreterManager.java:337)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:641)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:18:00.743
!MESSAGE Info: Rebuilding internal caches: C:\Users\Matthew\Development\Python\repos\CodeForGood2014\server_workspace\.metadata\.plugins\com.python.pydev.analysis\python_v1_18uivqhmb7t76vtsix84zcaw5\python.pydevsysteminfo (Expected error to be provided and got no error!)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:18:45.344
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\slicer\browser.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\slicer\browser.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:18:45.462
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\star.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\star.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:18:45.477
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\workspace.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\workspace.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:18:46.147
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\browser.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\browser.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:18:46.192
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\common.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\common.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:18:46.322
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\formatter.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\formatter.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:18:46.380
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\model.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\model.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:18:46.407
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\controllers.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\controllers.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:18:46.412
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\slicer.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\slicer.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:18:46.431
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\workspace.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\workspace.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:155)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:124)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:171)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:20:31.287
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\slicer\browser.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\slicer\browser.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:20:31.292
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\star.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\star.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:20:31.324
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\workspace.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\workspace.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:20:31.325
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\browser.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\browser.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:20:31.328
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\common.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\common.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:20:31.330
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\formatter.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\formatter.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:20:31.333
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\model.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\model.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:20:31.338
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\controllers.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\controllers.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:20:31.340
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\slicer.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\slicer.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:20:31.343
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\workspace.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\workspace.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:21:43.529
!MESSAGE Info: Rebuilding internal caches: C:\Users\Matthew\Development\Python\repos\CodeForGood2014\server_workspace\.metadata\.plugins\org.eclipse.core.resources\.projects\ChatServer\com.python.pydev.analysis\AdditionalProjectInterpreterInfo.pydevinfo (Expected error to be provided and got no error!)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 21:22:15.071
!MESSAGE ERROR reading shell.
ProcessInfo:

 - Executed: C:\Program Files\Anaconda\python.exe -u C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc\pycompletionserver.py 50617

 - Environment:
ACPATH=C:\Program Files (x86)\Lenovo\Access Connections\
ALCKPATH=C:\Program Files\Lenovo\AutoLock
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Matthew\AppData\Roaming
COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
COMMONPROGRAMFILES=C:\Program Files\Common Files
COMMONPROGRAMW6432=C:\Program Files\Common Files
COMMPATH=C:\Program Files\Lenovo\Communications Utility
COMPUTERNAME=MACTOP
COMSPEC=C:\Windows\system32\cmd.exe
FP_NO_HOST_CHECK=NO
HOMEDRIVE=C:
HOMEPATH=\Users\Matthew
LOCALAPPDATA=C:\Users\Matthew\AppData\Local
LOGONSERVER=\\MACTOP
MOZ_PLUGIN_PATH=C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\
NUMBER_OF_PROCESSORS=4
OS=Windows_NT
PATH=C:/Users/Matthew/introcs/java/bin/server;C:/Users/Matthew/introcs/java/bin;C:/Users/Matthew/introcs/java/lib/amd64;C:\Users\Matthew\introcs\java\bin;C:\Windows\SYSTEM32;C:\Windows;C:\Windows\SYSTEM32\WBEM;C:\Windows\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\PROGRAM FILES\INTEL\WIFI\BIN\;C:\PROGRAM FILES\COMMON FILES\INTEL\WIRELESSCOMMON\;C:\PROGRAM FILES (X86)\INTEL\OPENCL SDK\2.0\BIN\X86;C:\PROGRAM FILES (X86)\INTEL\OPENCL SDK\2.0\BIN\X64;C:\PROGRAM FILES (X86)\INTEL\SERVICES\IPT\;C:\PROGRAM FILES (X86)\COMMON FILES\LENOVO;C:\SWTOOLS\READYAPPS;C:\PROGRAM FILES\CONDUSIV TECHNOLOGIES\EXPRESSCACHE\;C:\Program Files\ThinkPad\Bluetooth Software\;C:\Program Files\ThinkPad\Bluetooth Software\syswow64;C:\Program Files (x86)\Lenovo\Access Connections\;C:\Program Files (x86)\Lenovo\Password Manager\;C:\Program Files\MATLAB\R2013b\runtime\win64;C:\Program Files\MATLAB\R2013b\bin;C:\Program Files\TortoiseHg\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files\Anaconda;C:\Program Files\Anaconda\Scripts;C:\Program Files\MySQL\MySQL Server 5.5\bin;C:\Users\Matthew\introcs\j3d\bin;C:\Users\Matthew\introcs\bin;C:\Users\Matthew\introcs\java\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Google\google_appengine\;C:\Users\Matthew\Development\Python\repos\probedb\AppEngine_workspace\AppEngineProject\probemanager\;C:\Program Files (x86)\Google\google_appengine;C:\Program Files (x86)\Google\google_appengine\lib;C:\Program Files\Anaconda\Scripts;C:\Program Files\Eclipse\Kepler\eclipse;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2a07
PROGRAMDATA=C:\ProgramData
PROGRAMFILES(X86)=C:\Program Files (x86)
PROGRAMFILES=C:\Program Files
PROGRAMW6432=C:\Program Files
PROMPT=$P$G
PSMODULEPATH=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\
PUBLIC=C:\Users\Public
PYTHONPATH=C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc\pydev_sitecustomize;C:\Program Files\Anaconda;C:\Users\Matthew\Development\Python\repos\probedb\AppEngine_workspace\AppEngineProject\probemanager;C:\Program Files\Anaconda\Lib\site-packages;C:\Program Files\Anaconda\DLLs;C:\Program Files\Anaconda\lib;C:\Program Files\Anaconda\lib\lib-tk;C:\Program Files\Anaconda\lib\site-packages\PIL;C:\Program Files\Anaconda\lib\site-packages\win32;C:\Program Files\Anaconda\lib\site-packages\win32\lib;C:\Program Files\Anaconda\lib\site-packages\Pythonwin;C:\Program Files\Anaconda\lib\site-packages\runipy-0.1.0-py2.7.egg;C:\Program Files\Anaconda\lib\site-packages\setuptools-3.6-py2.7.egg;C:\Program Files\Anaconda\Lib\site-packages\runipy-0.1.0-py2.7.egg;C:\Program Files\Anaconda\Lib\site-packages\setuptools-3.6-py2.7.egg
READYAPPS=C:\SWTOOLS\ReadyApps
SESSIONNAME=Console
SWSHARE=C:\SWSHARE
SYSTEMDRIVE=C:
SYSTEMROOT=C:\Windows
TEMP=C:\Users\Matthew\AppData\Local\Temp
TFS_DIR=C:\Program Files\ThinkVantage Fingerprint Software\
TMP=C:\Users\Matthew\AppData\Local\Temp
TRPATH=C:\Program Files (x86)\Lenovo\Screen Reading Optimizer\
TVTCOMMON=C:\Program Files (x86)\Common Files\Lenovo
USERDOMAIN=MacTop
USERDOMAIN_ROAMINGPROFILE=MacTop
USERNAME=Matthew
USERPROFILE=C:\Users\Matthew
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
VS90COMNTOOLS=c:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\
WINDIR=C:\Windows
WINDOWS_TRACING_FLAGS=3
WINDOWS_TRACING_LOGFILE=C:\BVTBin\Tests\installpackage\csilogfile.log

 - Working Dir:
C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc

 - OS:
Windows 7

 - Std output:


 - Err output:

!STACK 0
java.net.SocketTimeoutException
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(Unknown Source)
	at sun.nio.ch.ChannelInputStream.read(Unknown Source)
	at java.io.InputStream.read(Unknown Source)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.read(AbstractShell.java:454)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.read(AbstractShell.java:506)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.writeAndGetResults(AbstractShell.java:692)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getImportCompletions(AbstractShell.java:756)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createTokensFromServer(CompiledModule.java:362)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.<init>(CompiledModule.java:167)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getBuiltinModule(SystemModulesManager.java:309)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getModule(SystemModulesManager.java:348)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.updateKeysIfNeededAndSave(AbstractAdditionalDependencyInfo.java:236)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.synchInfoToPythonPath(InterpreterInfoBuilder.java:106)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.synchronizeManagerToNameToInfoPythonpath(SynchSystemModulesManager.java:391)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManagerScheduler$SynchJob.run(SynchSystemModulesManagerScheduler.java:260)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.eclipse.jface 2 0 2014-09-26 21:58:14.881
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2014-09-26 21:58:14.881
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@16337312,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@bc7ae21,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6278fe91,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)

!ENTRY org.eclipse.jface 2 0 2014-09-26 22:19:56.361
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2014-09-26 22:19:56.361
!MESSAGE A conflict occurred for CTRL+SHIFT+F:
Binding(CTRL+SHIFT+F,
	ParameterizedCommand(Command(org.eclipse.wst.sse.ui.format.document,Format,
		Format selection,
		Category(org.eclipse.ui.category.edit,Edit,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@47595955,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.wst.sse.ui.structuredTextEditorScope,,,system)
Binding(CTRL+SHIFT+F,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyFormatStd,Python Format Code,
		Format Code,
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@37c3afa1,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2014-09-26 22:19:56.361
!MESSAGE A conflict occurred for ALT+SHIFT+ARROW_UP:
Binding(ALT+SHIFT+ARROW_UP,
	ParameterizedCommand(Command(org.eclipse.wst.sse.ui.structure.select.enclosing,Select Enclosing Element,
		Expand selection to include enclosing element,
		Category(org.eclipse.ui.category.edit,Edit,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@4386f41e,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.wst.sse.ui.structuredTextEditorScope,,,system)
Binding(ALT+SHIFT+ARROW_UP,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.selectEnclosingScope,Select Enclosing Scope,
		Select Enclosing Scope,
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@103f8fa1,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2014-09-26 22:19:56.361
!MESSAGE A conflict occurred for CTRL+SHIFT+P:
Binding(CTRL+SHIFT+P,
	ParameterizedCommand(Command(org.eclipse.wst.sse.ui.goto.matching.bracket,Matching Character,
		Go to Matching Character,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@24aec30d,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.wst.sse.ui.structuredTextEditorScope,,,system)
Binding(CTRL+SHIFT+P,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.goToMatchingBracket,Go to Matching Bracket,
		Go to Matching Bracket,
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3cee9b5c,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2014-09-26 22:19:56.361
!MESSAGE A conflict occurred for CTRL+O:
Binding(CTRL+O,
	ParameterizedCommand(Command(org.eclipse.wst.sse.ui.quick_outline,Quick Outline,
		Show the quick outline for the editor input,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@5519d444,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.wst.sse.ui.structuredTextEditorScope,,,system)
Binding(CTRL+O,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowOutline,Python Show Outline,
		Show Outline,
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@12bee802,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2014-09-26 22:19:56.362
!MESSAGE A conflict occurred for F3:
Binding(F3,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.open.editor,Open Declaration,
		Open an editor on the selected element,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3371e4eb,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(F3,
	ParameterizedCommand(Command(org.eclipse.wst.sse.ui.open.file.from.source,Open Selection,
		Open an editor on the selected link,
		Category(org.eclipse.ui.category.edit,Edit,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@7a6c1aaf,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.wst.sse.ui.structuredTextEditorScope,,,system)
Binding(F3,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.navigation.pyGoToDefinition,Python Go To Definition,
		Goes to the definition of a python element,
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@4f4c15f3,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2014-09-26 22:19:56.362
!MESSAGE A conflict occurred for ALT+SHIFT+ARROW_DOWN:
Binding(ALT+SHIFT+ARROW_DOWN,
	ParameterizedCommand(Command(org.eclipse.wst.sse.ui.structure.select.last,Restore Last Selection,
		Restore last selection,
		Category(org.eclipse.ui.category.edit,Edit,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@4da8bb5d,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.wst.sse.ui.structuredTextEditorScope,,,system)
Binding(ALT+SHIFT+ARROW_DOWN,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.deselectEnclosingScope,Deselect Enclosing Scope,
		Deselect Enclosing Scope,
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@c352d31,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2014-09-26 22:19:56.362
!MESSAGE A conflict occurred for CTRL+SHIFT+ARROW_UP:
Binding(CTRL+SHIFT+ARROW_UP,
	ParameterizedCommand(Command(org.eclipse.wst.xml.ui.previousSibling,Previous Sibling,
		Go to Previous Sibling,
		Category(org.eclipse.ui.category.edit,Edit,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@50358b92,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.wst.sse.ui.structuredTextEditorScope,,,system)
Binding(CTRL+SHIFT+ARROW_UP,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.navigation.previousMethod,Previous Method or Class,
		Navigates to the previous method or class definition,
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@7729f239,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2014-09-26 22:19:56.362
!MESSAGE A conflict occurred for CTRL+SHIFT+ARROW_DOWN:
Binding(CTRL+SHIFT+ARROW_DOWN,
	ParameterizedCommand(Command(org.eclipse.wst.xml.ui.nextSibling,Next Sibling,
		Go to Next Sibling,
		Category(org.eclipse.ui.category.edit,Edit,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@653a5964,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.wst.sse.ui.structuredTextEditorScope,,,system)
Binding(CTRL+SHIFT+ARROW_DOWN,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.navigation.nextMethod,Next Method or Class,
		Navigates to the next method or class definition,
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@62ddb94d,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:32:28.902
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\slicer\browser.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\slicer\browser.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:32:28.947
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\star.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\star.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:32:28.962
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\workspace.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\workspace.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:32:28.993
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\browser.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\browser.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:32:29.008
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\common.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\common.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:32:29.013
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\formatter.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\formatter.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:32:29.041
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\model.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\model.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:32:29.084
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\controllers.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\controllers.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:32:29.089
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\slicer.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\slicer.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:32:29.108
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\workspace.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\workspace.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$3.run(AbstractInterpreterPreferencesPage.java:262)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:33:32.489
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\slicer\browser.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\slicer\browser.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:33:32.493
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\star.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\star.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:33:32.496
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\workspace.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\workspace.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:33:32.498
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\browser.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\browser.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:33:32.500
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\common.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\common.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:33:32.503
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\formatter.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\formatter.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:33:32.506
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\model.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\model.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:33:32.510
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\controllers.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\controllers.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:33:32.512
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\slicer.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\slicer.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:33:32.516
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\workspace.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\workspace.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:34:28.659
!MESSAGE ERROR reading shell.
ProcessInfo:

 - Executed: C:\Program Files\Anaconda\python.exe -u C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc\pycompletionserver.py 51081

 - Environment:
ACPATH=C:\Program Files (x86)\Lenovo\Access Connections\
ALCKPATH=C:\Program Files\Lenovo\AutoLock
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Matthew\AppData\Roaming
COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
COMMONPROGRAMFILES=C:\Program Files\Common Files
COMMONPROGRAMW6432=C:\Program Files\Common Files
COMMPATH=C:\Program Files\Lenovo\Communications Utility
COMPUTERNAME=MACTOP
COMSPEC=C:\Windows\system32\cmd.exe
FP_NO_HOST_CHECK=NO
HOMEDRIVE=C:
HOMEPATH=\Users\Matthew
LOCALAPPDATA=C:\Users\Matthew\AppData\Local
LOGONSERVER=\\MACTOP
MOZ_PLUGIN_PATH=C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\
NUMBER_OF_PROCESSORS=4
OS=Windows_NT
PATH=C:/Users/Matthew/introcs/java/bin/server;C:/Users/Matthew/introcs/java/bin;C:/Users/Matthew/introcs/java/lib/amd64;C:\Users\Matthew\introcs\java\bin;C:\Windows\SYSTEM32;C:\Windows;C:\Windows\SYSTEM32\WBEM;C:\Windows\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\PROGRAM FILES\INTEL\WIFI\BIN\;C:\PROGRAM FILES\COMMON FILES\INTEL\WIRELESSCOMMON\;C:\PROGRAM FILES (X86)\INTEL\OPENCL SDK\2.0\BIN\X86;C:\PROGRAM FILES (X86)\INTEL\OPENCL SDK\2.0\BIN\X64;C:\PROGRAM FILES (X86)\INTEL\SERVICES\IPT\;C:\PROGRAM FILES (X86)\COMMON FILES\LENOVO;C:\SWTOOLS\READYAPPS;C:\PROGRAM FILES\CONDUSIV TECHNOLOGIES\EXPRESSCACHE\;C:\Program Files\ThinkPad\Bluetooth Software\;C:\Program Files\ThinkPad\Bluetooth Software\syswow64;C:\Program Files (x86)\Lenovo\Access Connections\;C:\Program Files (x86)\Lenovo\Password Manager\;C:\Program Files\MATLAB\R2013b\runtime\win64;C:\Program Files\MATLAB\R2013b\bin;C:\Program Files\TortoiseHg\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files\Anaconda;C:\Program Files\Anaconda\Scripts;C:\Program Files\MySQL\MySQL Server 5.5\bin;C:\Users\Matthew\introcs\j3d\bin;C:\Users\Matthew\introcs\bin;C:\Users\Matthew\introcs\java\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Google\google_appengine\;C:\Users\Matthew\Development\Python\repos\probedb\AppEngine_workspace\AppEngineProject\probemanager\;C:\Program Files (x86)\Google\google_appengine;C:\Program Files (x86)\Google\google_appengine\lib;C:\Program Files\Anaconda\Scripts;C:\Program Files\Eclipse\Kepler\eclipse;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2a07
PROGRAMDATA=C:\ProgramData
PROGRAMFILES(X86)=C:\Program Files (x86)
PROGRAMFILES=C:\Program Files
PROGRAMW6432=C:\Program Files
PROMPT=$P$G
PSMODULEPATH=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\
PUBLIC=C:\Users\Public
PYTHONPATH=C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc\pydev_sitecustomize;C:\Program Files\Anaconda;C:\Program Files\Anaconda\Lib\site-packages;C:\Program Files\Anaconda\DLLs;C:\Program Files\Anaconda\lib;C:\Program Files\Anaconda\lib\lib-tk;C:\Program Files\Anaconda\lib\site-packages\PIL;C:\Program Files\Anaconda\lib\site-packages\win32;C:\Program Files\Anaconda\lib\site-packages\win32\lib;C:\Program Files\Anaconda\lib\site-packages\Pythonwin;C:\Program Files\Anaconda\lib\site-packages\runipy-0.1.0-py2.7.egg;C:\Program Files\Anaconda\lib\site-packages\setuptools-3.6-py2.7.egg;C:\Program Files\Anaconda\Lib\site-packages\runipy-0.1.0-py2.7.egg;C:\Program Files\Anaconda\Lib\site-packages\setuptools-3.6-py2.7.egg;C:\Users\Matthew\Development\Python\repos\probedb\AppEngine_workspace\AppEngineProject\probemanager
READYAPPS=C:\SWTOOLS\ReadyApps
SESSIONNAME=Console
SWSHARE=C:\SWSHARE
SYSTEMDRIVE=C:
SYSTEMROOT=C:\Windows
TEMP=C:\Users\Matthew\AppData\Local\Temp
TFS_DIR=C:\Program Files\ThinkVantage Fingerprint Software\
TMP=C:\Users\Matthew\AppData\Local\Temp
TRPATH=C:\Program Files (x86)\Lenovo\Screen Reading Optimizer\
TVTCOMMON=C:\Program Files (x86)\Common Files\Lenovo
USERDOMAIN=MacTop
USERDOMAIN_ROAMINGPROFILE=MacTop
USERNAME=Matthew
USERPROFILE=C:\Users\Matthew
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
VS90COMNTOOLS=c:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\
WINDIR=C:\Windows
WINDOWS_TRACING_FLAGS=3
WINDOWS_TRACING_LOGFILE=C:\BVTBin\Tests\installpackage\csilogfile.log

 - Working Dir:
C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc

 - OS:
Windows 7

 - Std output:


 - Err output:
AccessInit: hash collision: 3 for both 1 and 1

!STACK 0
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(Unknown Source)
	at sun.nio.ch.ChannelInputStream.read(Unknown Source)
	at java.io.InputStream.read(Unknown Source)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.read(AbstractShell.java:454)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.read(AbstractShell.java:506)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.writeAndGetResults(AbstractShell.java:692)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getImportCompletions(AbstractShell.java:756)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createTokensFromServer(CompiledModule.java:362)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.<init>(CompiledModule.java:167)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getBuiltinModule(SystemModulesManager.java:296)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getModule(SystemModulesManager.java:348)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.updateKeysIfNeededAndSave(AbstractAdditionalDependencyInfo.java:236)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.synchInfoToPythonPath(InterpreterInfoBuilder.java:106)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.synchronizeManagerToNameToInfoPythonpath(SynchSystemModulesManager.java:391)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManagerScheduler$SynchJob.run(SynchSystemModulesManagerScheduler.java:260)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
!SESSION 2014-09-26 22:36:03.525 -----------------------------------------------
eclipse.buildId=4.3.2.M20140221-1700
java.version=1.7.0_67
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.standard.product -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.standard.product -data C:\Users\Matthew\Development\Python\repos\CodeForGood2014\server_workspace -product org.eclipse.epp.package.standard.product

!ENTRY org.eclipse.ui.navigator 2 0 2014-09-26 22:36:16.868
!MESSAGE Can't find Navigator Content Descriptor with id: org.eclipse.jst.servlet.ui.EnhancedJavaRendering

!ENTRY org.eclipse.egit.ui 2 0 2014-09-26 22:36:29.016
!MESSAGE Warning: EGit couldn't detect the installation path "gitPrefix" of native Git. Hence EGit can't respect system level
Git settings which might be configured in ${gitPrefix}/etc/gitconfig under the native Git installation directory.
The most important of these settings is core.autocrlf. Git for Windows by default sets this parameter to true in
this system level configuration. The Git installation location can be configured on the
Team > Git > Configuration preference page's 'System Settings' tab.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.egit.ui 2 0 2014-09-26 22:36:29.018
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\Matthew'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:37:05.367
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\slicer\browser.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\slicer\browser.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:37:05.373
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\star.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\star.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:37:05.377
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\workspace.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\backends\sql\workspace.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:37:05.380
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\browser.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\browser.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:37:05.383
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\common.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\common.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:37:05.387
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\formatter.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\formatter.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:37:05.391
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\model.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\model.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:37:05.397
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\controllers.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\controllers.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:37:05.400
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\slicer.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\server\slicer.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:37:05.404
!MESSAGE The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\workspace.py is not a valid encoding.
!STACK 0
java.io.UnsupportedEncodingException: The encoding found: >>utf<< on C:\Program Files\Anaconda\Lib\site-packages\cubes\workspace.py is not a valid encoding.
	at org.python.pydev.shared_core.io.FileUtils.getValidEncoding(FileUtils.java:705)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:666)
	at org.python.pydev.shared_core.io.FileUtils.getPythonFileEncoding(FileUtils.java:736)
	at org.python.pydev.core.FileUtilsFileBuffer.getCustomReturnFromFile(FileUtilsFileBuffer.java:172)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalTokensInfo.addAstInfo(AbstractAdditionalTokensInfo.java:282)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalInfoWithBuild.restoreInfoForModuleManager(AbstractAdditionalInfoWithBuild.java:258)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.recreateAllInfo(AdditionalSystemInterpreterInfo.java:179)
	at com.python.pydev.analysis.additionalinfo.builders.InterpreterObserver.notifyDefaultPythonpathRestored(InterpreterObserver.java:35)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.restorePythopathForInterpreters(AbstractInterpreterManager.java:726)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:643)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.applySelectedChangesToInterpreterInfosPythonpath(SynchSystemModulesManager.java:219)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$JobApplyChanges.run(SynchSystemModulesManager.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.python.pydev.shared_core 4 4 2014-09-26 22:37:34.620
!MESSAGE ERROR reading shell.
ProcessInfo:

 - Executed: C:\Program Files\Anaconda\python.exe -u C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc\pycompletionserver.py 51153

 - Environment:
ACPATH=C:\Program Files (x86)\Lenovo\Access Connections\
ALCKPATH=C:\Program Files\Lenovo\AutoLock
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Matthew\AppData\Roaming
COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
COMMONPROGRAMFILES=C:\Program Files\Common Files
COMMONPROGRAMW6432=C:\Program Files\Common Files
COMMPATH=C:\Program Files\Lenovo\Communications Utility
COMPUTERNAME=MACTOP
COMSPEC=C:\Windows\system32\cmd.exe
FP_NO_HOST_CHECK=NO
HOMEDRIVE=C:
HOMEPATH=\Users\Matthew
LOCALAPPDATA=C:\Users\Matthew\AppData\Local
LOGONSERVER=\\MACTOP
MOZ_PLUGIN_PATH=C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\
NUMBER_OF_PROCESSORS=4
OS=Windows_NT
PATH=C:/Users/Matthew/introcs/java/bin/server;C:/Users/Matthew/introcs/java/bin;C:/Users/Matthew/introcs/java/lib/amd64;C:\Users\Matthew\introcs\java\bin;C:\Windows\SYSTEM32;C:\Windows;C:\Windows\SYSTEM32\WBEM;C:\Windows\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\PROGRAM FILES\INTEL\WIFI\BIN\;C:\PROGRAM FILES\COMMON FILES\INTEL\WIRELESSCOMMON\;C:\PROGRAM FILES (X86)\INTEL\OPENCL SDK\2.0\BIN\X86;C:\PROGRAM FILES (X86)\INTEL\OPENCL SDK\2.0\BIN\X64;C:\PROGRAM FILES (X86)\INTEL\SERVICES\IPT\;C:\PROGRAM FILES (X86)\COMMON FILES\LENOVO;C:\SWTOOLS\READYAPPS;C:\PROGRAM FILES\CONDUSIV TECHNOLOGIES\EXPRESSCACHE\;C:\Program Files\ThinkPad\Bluetooth Software\;C:\Program Files\ThinkPad\Bluetooth Software\syswow64;C:\Program Files (x86)\Lenovo\Access Connections\;C:\Program Files (x86)\Lenovo\Password Manager\;C:\Program Files\MATLAB\R2013b\runtime\win64;C:\Program Files\MATLAB\R2013b\bin;C:\Program Files\TortoiseHg\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files\Anaconda;C:\Program Files\Anaconda\Scripts;C:\Program Files\MySQL\MySQL Server 5.5\bin;C:\Users\Matthew\introcs\j3d\bin;C:\Users\Matthew\introcs\bin;C:\Users\Matthew\introcs\java\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Google\google_appengine\;C:\Users\Matthew\Development\Python\repos\probedb\AppEngine_workspace\AppEngineProject\probemanager\;C:\Program Files (x86)\Google\google_appengine;C:\Program Files (x86)\Google\google_appengine\lib;C:\Program Files\Anaconda\Scripts;C:\Program Files\Eclipse\Kepler\eclipse;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2a07
PROGRAMDATA=C:\ProgramData
PROGRAMFILES(X86)=C:\Program Files (x86)
PROGRAMFILES=C:\Program Files
PROGRAMW6432=C:\Program Files
PROMPT=$P$G
PSMODULEPATH=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\
PUBLIC=C:\Users\Public
PYTHONPATH=C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc\pydev_sitecustomize;C:\Program Files\Anaconda;C:\Program Files\Anaconda\Lib\site-packages;C:\Program Files\Anaconda\DLLs;C:\Program Files\Anaconda\lib;C:\Program Files\Anaconda\lib\lib-tk;C:\Program Files\Anaconda\lib\site-packages\PIL;C:\Program Files\Anaconda\lib\site-packages\win32;C:\Program Files\Anaconda\lib\site-packages\win32\lib;C:\Program Files\Anaconda\lib\site-packages\Pythonwin;C:\Program Files\Anaconda\lib\site-packages\runipy-0.1.0-py2.7.egg;C:\Program Files\Anaconda\lib\site-packages\setuptools-3.6-py2.7.egg;C:\Program Files\Anaconda\Lib\site-packages\runipy-0.1.0-py2.7.egg;C:\Program Files\Anaconda\Lib\site-packages\setuptools-3.6-py2.7.egg;C:\Users\Matthew\Development\Python\repos\probedb\AppEngine_workspace\AppEngineProject\probemanager
READYAPPS=C:\SWTOOLS\ReadyApps
SESSIONNAME=Console
SWSHARE=C:\SWSHARE
SYSTEMDRIVE=C:
SYSTEMROOT=C:\Windows
TEMP=C:\Users\Matthew\AppData\Local\Temp
TFS_DIR=C:\Program Files\ThinkVantage Fingerprint Software\
TMP=C:\Users\Matthew\AppData\Local\Temp
TRPATH=C:\Program Files (x86)\Lenovo\Screen Reading Optimizer\
TVTCOMMON=C:\Program Files (x86)\Common Files\Lenovo
USERDOMAIN=MacTop
USERDOMAIN_ROAMINGPROFILE=MacTop
USERNAME=Matthew
USERPROFILE=C:\Users\Matthew
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
VS90COMNTOOLS=c:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\
WINDIR=C:\Windows
WINDOWS_TRACING_FLAGS=3
WINDOWS_TRACING_LOGFILE=C:\BVTBin\Tests\installpackage\csilogfile.log

 - Working Dir:
C:\Users\Matthew\.eclipse\org.eclipse.platform_4.3.2_1593202263_win32_win32_x86_64\plugins\org.python.pydev_3.5.0.201405201709\pysrc

 - OS:
Windows 7

 - Std output:


 - Err output:
AccessInit: hash collision: 3 for both 1 and 1

!STACK 0
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(Unknown Source)
	at sun.nio.ch.ChannelInputStream.read(Unknown Source)
	at java.io.InputStream.read(Unknown Source)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.read(AbstractShell.java:454)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.read(AbstractShell.java:506)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.writeAndGetResults(AbstractShell.java:692)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getImportCompletions(AbstractShell.java:756)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createTokensFromServer(CompiledModule.java:362)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.<init>(CompiledModule.java:167)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getBuiltinModule(SystemModulesManager.java:296)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getModule(SystemModulesManager.java:348)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.updateKeysIfNeededAndSave(AbstractAdditionalDependencyInfo.java:236)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.synchInfoToPythonPath(InterpreterInfoBuilder.java:106)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.synchronizeManagerToNameToInfoPythonpath(SynchSystemModulesManager.java:391)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManagerScheduler$SynchJob.run(SynchSystemModulesManagerScheduler.java:260)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.eclipse.jface 2 0 2014-09-26 22:37:42.086
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2014-09-26 22:37:42.086
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@39ef8678,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(com.python.pydev.analysis.actions.pyGlobalsBrowserWorkbench,Python Show Global Tokens (Global),
		Python Show Global Tokens (Global),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@1c654dff,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.python.pydev.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.pyShowBrowser,Python Show Global Tokens (Editor),
		Python Show Global Tokens (Editor),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3ee3aee9,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)
